name: serv_oeste
description: "Front-end da Serv-Oeste"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  masked_text: ^1.1.2
  logger: ^2.2.0
  drop_down_search_field: ^1.0.4
  super_sliver_list: ^0.4.1
  animated_custom_dropdown: ^3.1.1
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0
  dio: ^5.7.0
  dio_cookie_manager: ^3.0.1
  cookie_jar: ^4.0.1
  path_provider: ^2.1.1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  meta: ^1.15.0
  lucid_validation: ^1.1.0
  mask_text_input_formatter: ^2.9.0
  provider: ^6.1.2
  pluto_grid: ^8.0.0
  diacritic: ^0.1.3
  pdf: ^3.10.7
  printing: ^5.12.0
  skeletonizer: ^2.1.0+1
  dartz: ^0.10.1
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/servOeste.png
    - assets/heroImage.png
    - assets/addService.png
