name: serv_oeste
description: "Front-end da Serv-Oeste"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_custom_dropdown: ^3.1.1
  bloc: ^9.2.0
  collection: ^1.19.1
  cookie_jar: ^4.0.8
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.9.1
  dio_cookie_manager: ^3.3.0
  drop_down_search_field: ^1.2.2+1
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^10.0.0
  http: ^1.6.0
  intl: ^0.20.2
  logger: ^2.2.0
  lucid_validation: ^1.3.1
  masked_text: ^1.1.2
  mask_text_input_formatter: ^2.9.0
  meta: ^1.17.0
  pdf: ^3.11.3
  pluto_grid: ^8.1.0
  printing: ^5.14.2
  provider: ^6.1.5+1
  skeletonizer: ^2.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/servOeste.png
    - assets/heroImage.png
    - assets/addService.png
